# Generated by Django 3.0.4 on 2020-10-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageurl',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
