# Generated by Django 3.0.4 on 2020-11-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201031_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageraw',
            old_name='created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='pagetext',
            old_name='created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='pageurl',
            old_name='created',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='pageraw',
            name='html_hashed',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageraw',
            name='is_changed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='is_changed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagetext',
            name='text_hashed',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageurl',
            name='last_error_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pageurl',
            name='last_error_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pageurl',
            name='last_parsed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pageurl',
            name='last_polled_on',
            field=models.DateTimeField(null=True),
        ),
    ]
