# Generated by Django 3.0.4 on 2020-11-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201101_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageurl',
            name='last_change_on',
            field=models.DateTimeField(null=True),
        ),
    ]
