# Generated by Django 3.0.4 on 2020-11-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pageurl_last_change_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagetext',
            name='is_changed',
        ),
        migrations.AddField(
            model_name='pagetext',
            name='html',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='html_hashed',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='is_html_changed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='is_text_changed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pagetext',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pagetext',
            name='text_hashed',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.DeleteModel(
            name='PageRaw',
        ),
    ]
