# Generated by Django 3.0.4 on 2020-11-01 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201101_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetext',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='main.PageUrl'),
        ),
    ]
