# Generated by Django 3.0.4 on 2020-11-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201101_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageurl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pagetext',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
