# Generated by Django 3.0.4 on 2020-11-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201101_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagetext',
            old_name='html',
            new_name='_html',
        ),
        migrations.RenameField(
            model_name='pagetext',
            old_name='text',
            new_name='_text',
        ),
    ]
