# Generated by Django 3.0.4 on 2020-11-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201110_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageurl',
            name='author',
            field=models.CharField(default='', max_length=500),
        ),
    ]
