# Generated by Django 3.1.3 on 2020-11-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pageurl_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageurl',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
